### PR TITLE
A workaround for linker errors on Windows

### PR DESCRIPTION
**Pull request by marcinmrotek**
I'm not sure if you want this in hmatrix proper, but 've experienced some weird linker errors like "unknown symbol atanh" when trying to compile my package that depends on hmatrix. I've added a workaround that conditionally disables some functions from vector-aux.c. The same tests pass with and without the workaround.

### CODE REVIEW

**Comment by albertoruiz** [comment]
Thank you for your work. I have a question: don't you think that removing those functions (mapR, etc.) is too drastic? It would be much better if we find the missing functions. I cannot test in Windows, but I think that a reasonably standard C library with atanh and the other missing functions must be available.

**Comment by marcinmrotek** [comment]
Yeah, that was supposed to be just a temporary solution, to get at least some of hmatrix's functionality to work. I'm not sure how to link against a library that has these functions without causing conflicts for other symbols, though (atanh and friends are supposed to be in libc, I think?)

**Comment by marcinmrotek** [comment]
Update: this might be related to this Stack issue: https://github.com/commercialhaskell/stack/issues/1279 (I was using Stack to build the project that

**Comment by idontgetoutmuch** [comment]
@marcinmrotek I think this is past its "sell by" date. Do you have any objections to me closing this?

**Pull request closed without merging**
