### PR TITLE
Stack build support for base package

### PR DESCRIPTION
**Pull request by varosi**
It is working and tested on Windows 10 x64 with OpenBLAS. 
LTS-3.3 resolver is used

It is branched from previous feature/windows_builds branch. So it is preferably previous pull request to be applied first: https://github.com/albertoruiz/hmatrix/pull/148

### CODE REVIEW

**Comment by razvan-panda** [comment]
:+1: Thank you!

**Comment by albertoruiz** [comment]
It is fantastic to have support for stack!
Thanks a lot for the contribution!

**Comment by varosi** [comment]
No problem! I'll try to make other modules to be buildable with Stack, too.

**Comment by varosi** [comment]
You're welcome!

2015-09-12 20:22 GMT+03:00 Alberto Ruiz <notifications@github.com>:

**Pull request merged**
