### PR TITLE
Support triangular matrices.

### PR DESCRIPTION
**Pull request by idontgetoutmuch**
Let me know what sort of tests I should add.

### CODE REVIEW

**Comment by albertoruiz** [comment]
Excellent, thanks!

**Comment by albertoruiz** [comment]
It would be nice to add a few unit tests with small matrices.

**Comment by idontgetoutmuch** [comment]
Done in the PR I just made. I hope you like the MathJax documentation :)

**Comment by albertoruiz** [comment]
Merged. I like it!

**Pull request merged**
