### PR TITLE
Fix windows support #125

### PR DESCRIPTION
**Pull request by NightRa**
This is supposed to fix the windows support #125 for hmatrix.
Please test this on windows & linux.

### CODE REVIEW

**Comment by NightRa** [comment]
This wasn't finished. The work on this issue should be continued.

**Comment by albertoruiz** [comment]
In any case, thanks for your help!
I can't test on windows at the moment, but I will try to set up a virtual machine for testing when I finish other changes to the library.

**Comment by albertoruiz** [comment]
I am not sure if we should keep these changes and include them in the next release, or it is better that we revert the commits and wait until the issue is fully solved. What do you think?

**Comment by NightRa** [comment]
Better revert the changes and wait until it's fully resolved.

**Pull request merged**
