### PR TITLE
Fixed #125 build under Windows

### LINKED ISSUE #125: Build failure Windows GHC 7.8 32bit
Using the given dlls package, the build fails with the following:
```
[33 of 33] Compiling Numeric.LinearAlgebra.Static ( src\Numeric\LinearAlgebra\Static.hs, dist\dist-sandbox-3695bf19\build\Numeric\LinearAlgebra\Static.o )

src\C\vector-aux.c:766:30:
     warning: 'struct random_data' declared inside parameter list

src\C\vector-aux.c:766:30:
     warning: its scope is only this definition or declaration, which is probably not what you want
src\C\vector-aux.c: In function 'urandom':

src\C\vector-aux.c:768:5:
     warning: implicit declaration of function 'random_r'
src\C\vector-aux.c: At top level:

src\C\vector-aux.c:775:18:
     warning: 'struct random_data' declared inside parameter list
src\C\vector-aux.c: In function 'gaussrand':

src\C\vector-aux.c:782:13:
     warning: passing argument 1 of 'urandom' from incompatible pointer type

src\C\vector-aux.c:766:15:
     note: expected 'struct random_data *' but argument is of type 'struct random_data *'

src\C\vector-aux.c:783:4:
     warning: passing argument 1 of 'urandom' from incompatible pointer type

src\C\vector-aux.c:766:15:
     note: expected 'struct random_data *' but argument is of type 'struct random_data *'
src\C\vector-aux.c: In function 'random_vector':

src\C\vector-aux.c:802:24:
     error: storage size of 'buffer' isn't known

src\C\vector-aux.c:804:31:
     error: invalid application of 'sizeof' to incomplete type 'struct random_data'

src\C\vector-aux.c:807:5:
     warning: implicit declaration of function 'initstate_r'

src\C\vector-aux.c:802:24:  warning: unused variable 'buffer'
```

### PR DESCRIPTION
**Pull request by varosi**
I was not wrote it well last time.

### CODE REVIEW

**Comment by varosi** [comment]
I have added fix for Windows. Actually Windows compilation works with FreeBSD and OSX versions.

**Comment by varosi** [comment]
@albertoruiz, did you thought about to use some Haskell library for random numbers generation, like:
http://hackage.haskell.org/package/AC-Random
or 
http://hackage.haskell.org/package/tf-random
which are not dependent on external C functions?

**Comment by razvan-panda** [comment]
@varosi Did you manage to get it built with stack also?

**Comment by varosi** [comment]
See this: https://github.com/commercialhaskell/stack/issues/983
Currently hmatrix has no stack.yaml configuration for building with Stack. I could make it in another pull request.

**Comment by razvan-panda** [comment]
@varosi Thank you for reply, I posted the yaml config on that issue. Nothing that I tried managed to detect the required libs during build.

**Comment by razvan-panda** [comment]
This works fine for building latest hmatrix.
Did you by any chance happen to build subhask also? It is another dependency needed for HLearn that needs hmatrix 0.16.1.5 and it fails to build when applying your build/stack related patches over  hmatrix 0.16.1.5. More details in: https://github.com/mikeizbicki/subhask/issues/22

**Comment by albertoruiz** [comment]
Thanks!
@varosi: In relation to the random numbers, there is of course no problem using other packages. I would like to have a simple and fast reentrant method to get big random arrays, but it is difficult to have something simple and portable in C. I will take a look at those packages, looking for a fast way to fill a vector.

**Comment by varosi** [comment]
Great! AC-Random looks good. If Vector could be Foldable it will be easy.

**Comment by albertoruiz** [comment]
There is also mwc-random, which also looks very good. It can obtain directly (uniform) vectors, and the elements can also be filled using safe mutation in the ST monad:

    import System.Random.MWC
    import qualified System.Random.MWC.Distributions as D
    import Numeric.LinearAlgebra
    import Numeric.LinearAlgebra.Devel
    
    rvec :: Vector Double
    rvec = runSTVector $ do
        v <- newUndefinedVector 10
        g <- initialize (fromList [4, 8, 15, 16, 23, 42])
        mapM_ (\k -> writeVector v k =<< D.standard g) [0..9]
        return v

We just need a simple way to supply the seed.

**Comment by varosi** [comment]
Is it possible to upload latest hmatrix version (with Windows support) to Hackage? I would like packages like SubHask to use that version.

**Comment by albertoruiz** [comment]
Yes, I will upload them very shortly.

**Comment by varosi** [comment]
Great!

**Pull request merged**
